### ISSUE TITLE
import metabase error: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by TomTrinh** [STUnitas/metabase-py#2]
I had the error when running code line:

from metabase import Metabase
  File "C:\ProgramData\Anaconda2\lib\site-packages\metabase\metabase.py", line 8
    def __init__(self, *args, endpoint='http://localhost:3000', email=None,
                                     ^
SyntaxError: invalid syntax

Can you help to check it?

**Comment by flrngel** [comment]
seems error comes from python version problem. this repo is tested on python3
