### ISSUE TITLE
JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by shreyarora150** [STUnitas/metabase-py#7]
I'm trying to execute a POST call 'api/card/card-id/query/csv' with the following payload:
payload={
        'dataset_query': {
            'database': 2,
            'native': {
                'query': ' SELECT "public"."TransactionEngine_transaction"."txn_id" AS "txn_id", "public"."TransactionEngine_transaction"."actor_id" AS "actor_id", "public"."TransactionEngine_transaction"."amount" AS "amount", "public"."TransactionEngine_transaction"."approval_status_id" AS "approval_status_id", "public"."TransactionEngine_transaction"."approved_amount" AS "approved_amount", "public"."TransactionEngine_transaction"."approved_currency_amount" AS "approved_currency_amount", "public"."TransactionEngine_transaction"."approved_date" AS "approved_date", "public"."TransactionEngine_transaction"."attached_on" AS "attached_on", "public"."TransactionEngine_transaction"."auth_code" AS "auth_code", "public"."TransactionEngine_transaction"."card_id" AS "card_id", "public"."TransactionEngine_transaction"."category_id" AS "category_id", "public"."TransactionEngine_transaction"."channel" AS "channel", "public"."TransactionEngine_transaction"."city_id" AS "city_id", "public"."TransactionEngine_transaction"."comments" AS "comments", "public"."TransactionEngine_transaction"."conversion_id" AS "conversion_id", "public"."TransactionEngine_transaction"."country_id" AS "country_id", "public"."TransactionEngine_transaction"."created_on" AS "created_on", "public"."TransactionEngine_transaction"."curr_merchant_balance" AS "curr_merchant_balance", "public"."TransactionEngine_transaction"."currency" AS "currency", "public"."TransactionEngine_transaction"."currency_amount" AS "currency_amount", "public"."TransactionEngine_transaction"."currency_link_id" AS "currency_link_id", "public"."TransactionEngine_transaction"."description" AS "description", "public"."TransactionEngine_transaction"."end_date" AS "end_date", "public"."TransactionEngine_transaction"."exchangeable_parent_id" AS "exchangeable_parent_id", "public"."TransactionEngine_transaction"."exported_to" AS "exported_to", "public"."TransactionEngine_transaction"."imported" AS "imported", "public"."TransactionEngine_transaction"."is_deleted" AS "is_deleted", "public"."TransactionEngine_transaction"."is_fee" AS "is_fee", "public"."TransactionEngine_transaction"."iso_field" AS "iso_field", "public"."TransactionEngine_transaction"."limit_string" AS "limit_string", "public"."TransactionEngine_transaction"."local_txn_id" AS "local_txn_id", "public"."TransactionEngine_transaction"."mcc" AS "mcc", "public"."TransactionEngine_transaction"."merchant_id" AS "merchant_id", "public"."TransactionEngine_transaction"."merchant_txn_id" AS "merchant_txn_id", "public"."TransactionEngine_transaction"."metadata" AS "metadata", "public"."TransactionEngine_transaction"."org_id" AS "org_id", "public"."TransactionEngine_transaction"."org_wallet_id" AS "org_wallet_id", "public"."TransactionEngine_transaction"."parent_id" AS "parent_id", "public"."TransactionEngine_transaction"."payee_merchant" AS "payee_merchant", "public"."TransactionEngine_transaction"."points" AS "points", "public"."TransactionEngine_transaction"."policy_json" AS "policy_json", "public"."TransactionEngine_transaction"."pre_merchant_balance" AS "pre_merchant_balance", "public"."TransactionEngine_transaction"."prev_wallet" AS "prev_wallet", "public"."TransactionEngine_transaction"."reimbursed" AS "reimbursed", "public"."TransactionEngine_transaction"."remarks" AS "remarks", "public"."TransactionEngine_transaction"."report_id" AS "report_id", "public"."TransactionEngine_transaction"."rrn" AS "rrn", "public"."TransactionEngine_transaction"."source_id" AS "source_id", "public"."TransactionEngine_transaction"."stan" AS "stan", "public"."TransactionEngine_transaction"."start_date" AS "start_date", "public"."TransactionEngine_transaction"."status" AS "status", "public"."TransactionEngine_transaction"."txn_date" AS "txn_date", "public"."TransactionEngine_transaction"."txn_type_id" AS "txn_type_id", "public"."TransactionEngine_transaction"."updated_on" AS "updated_on", "public"."TransactionEngine_transaction"."user_id" AS "user_id", "public"."TransactionEngine_transaction"."wallet_id" AS "wallet_id" FROM "public"."TransactionEngine_transaction" WHERE CAST("public"."TransactionEngine_transaction"."approved_date" AS date) = CAST(? AS date);'},
            'type': 'native',
            'parameters':[]}}

The above call throws the following error:
raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**My goal is to download the table (card) as a csv/json file**

**Comment by flrngel** [comment]
should track why server gives "None". Can you simulate above with using curl?
